<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class VilleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $villes = [
            ['ville' => 'Aïn Harrouda', 'region_id' => 6],
            ['ville' => 'Ben Yakhlef', 'region_id' => 6],
            ['ville' => 'Bouskoura', 'region_id' => 6],
            ['ville' => 'Casablanca', 'region_id' => 6],
            ['ville' => 'Médiouna', 'region_id' => 6],
            ['ville' => 'Mohammadia', 'region_id' => 6],
            ['ville' => 'Tit Mellil', 'region_id' => 6],
            ['ville' => 'Bejaâd', 'region_id' => 5],
            ['ville' => 'Ben Ahmed', 'region_id' => 6],
            ['ville' => 'Benslimane', 'region_id' => 6],
            ['ville' => 'Berrechid', 'region_id' => 6],
            ['ville' => 'Boujniba', 'region_id' => 5],
            ['ville' => 'Boulanouare', 'region_id' => 5],
            ['ville' => 'Bouznika', 'region_id' => 6],
            ['ville' => 'Deroua', 'region_id' => 6],
            ['ville' => 'El Borouj', 'region_id' => 6],
            ['ville' => 'El Gara', 'region_id' => 6],
            ['ville' => 'Guisser', 'region_id' => 6],
            ['ville' => 'Hattane', 'region_id' => 5],
            ['ville' => 'Khouribga', 'region_id' => 5],
            ['ville' => 'Loulad', 'region_id' => 6],
            ['ville' => 'Oued Zem', 'region_id' => 5],
            ['ville' => 'Oulad Abbou', 'region_id' => 6],
            ['ville' => 'Oulad H\'Riz Sahel', 'region_id' => 6],
            ['ville' => 'Oulad M\'rah', 'region_id' => 6],
            ['ville' => 'Oulad Saïd', 'region_id' => 6],
            ['ville' => 'Oulad Sidi Ben Daoud', 'region_id' => 6],
            ['ville' => 'Ras El Aïn', 'region_id' => 6],
            ['ville' => 'Settat', 'region_id' => 6],
            ['ville' => 'Sidi Rahhal Chataï', 'region_id' => 6],
            ['ville' => 'Soualem', 'region_id' => 6],
            ['ville' => 'Azemmour', 'region_id' => 6],
            ['ville' => 'Bir Jdid', 'region_id' => 6],
            ['ville' => 'Bouguedra', 'region_id' => 7],
            ['ville' => 'Echemmaia', 'region_id' => 7],
            ['ville' => 'El Jadida', 'region_id' => 6],
            ['ville' => 'Hrara', 'region_id' => 7],
            ['ville' => 'Ighoud', 'region_id' => 7],
            ['ville' => 'Jamâat Shaim', 'region_id' => 7],
            ['ville' => 'Jorf Lasfar', 'region_id' => 6],
            ['ville' => 'Khemis Zemamra', 'region_id' => 6],
            ['ville' => 'Laaounate', 'region_id' => 6],
            ['ville' => 'Moulay Abdallah', 'region_id' => 6],
            ['ville' => 'Oualidia', 'region_id' => 6],
            ['ville' => 'Oulad Amrane', 'region_id' => 6],
            ['ville' => 'Oulad Frej', 'region_id' => 6],
            ['ville' => 'Oulad Ghadbane', 'region_id' => 6],
            ['ville' => 'Safi', 'region_id' => 7],
            ['ville' => 'Sebt El Maârif', 'region_id' => 6],
            ['ville' => 'Sebt Gzoula', 'region_id' => 7],
            ['ville' => 'Sidi Ahmed', 'region_id' => 7],
            ['ville' => 'Sidi Ali Ban Hamdouche', 'region_id' => 6],
            ['ville' => 'Sidi Bennour', 'region_id' => 6],
            ['ville' => 'Sidi Bouzid', 'region_id' => 6],
            ['ville' => 'Sidi Smaïl', 'region_id' => 6],
            ['ville' => 'Youssoufia', 'region_id' => 7],
            ['ville' => 'Fès', 'region_id' => 3],
            ['ville' => 'Aïn Cheggag', 'region_id' => 3],
            ['ville' => 'Bhalil', 'region_id' => 3],
            ['ville' => 'Boulemane', 'region_id' => 3],
            ['ville' => 'El Menzel', 'region_id' => 3],
            ['ville' => 'Guigou', 'region_id' => 3],
            ['ville' => 'Imouzzer Kandar', 'region_id' => 3],
            ['ville' => 'Imouzzer Marmoucha', 'region_id' => 3],
            ['ville' => 'Missour', 'region_id' => 3],
            ['ville' => 'Moulay Yaâcoub', 'region_id' => 3],
            ['ville' => 'Ouled Tayeb', 'region_id' => 3],
            ['ville' => 'Outat El Haj', 'region_id' => 3],
            ['ville' => 'Ribate El Kheir', 'region_id' => 3],
            ['ville' => 'Séfrou', 'region_id' => 3],
            ['ville' => 'Skhinate', 'region_id' => 3],
            ['ville' => 'Tafajight', 'region_id' => 3],
            ['ville' => 'Arbaoua', 'region_id' => 4],
            ['ville' => 'Aïn Dorij', 'region_id' => 1],
            ['ville' => 'Dar Gueddari', 'region_id' => 4],
            ['ville' => 'Had Kourt', 'region_id' => 4],
            ['ville' => 'Jorf El Melha', 'region_id' => 4],
            ['ville' => 'Kénitra', 'region_id' => 4],
            ['ville' => 'Khenichet', 'region_id' => 4],
            ['ville' => 'Lalla Mimouna', 'region_id' => 4],
            ['ville' => 'Mechra Bel Ksiri', 'region_id' => 4],
            ['ville' => 'Mehdia', 'region_id' => 4],
            ['ville' => 'Moulay Bousselham', 'region_id' => 4],
            ['ville' => 'Sidi Allal Tazi', 'region_id' => 4],
            ['ville' => 'Sidi Kacem', 'region_id' => 4],
            ['ville' => 'Sidi Slimane', 'region_id' => 4],
            ['ville' => 'Sidi Taibi', 'region_id' => 4],
            ['ville' => 'Sidi Yahya El Gharb', 'region_id' => 4],
            ['ville' => 'Souk El Arbaa', 'region_id' => 4],
            ['ville' => 'Akka', 'region_id' => 9],
            ['ville' => 'Assa', 'region_id' => 10],
            ['ville' => 'Bouizakarne', 'region_id' => 10],
            ['ville' => 'El Ouatia', 'region_id' => 10],
            ['ville' => 'Es-Semara', 'region_id' => 11],
            ['ville' => 'Fam El Hisn', 'region_id' => 9],
            ['ville' => 'Foum Zguid', 'region_id' => 9],
            ['ville' => 'Guelmim', 'region_id' => 10],
            ['ville' => 'Taghjijt', 'region_id' => 10],
            ['ville' => 'Tan-Tan', 'region_id' => 10],
            ['ville' => 'Tata', 'region_id' => 9],
            ['ville' => 'Zag', 'region_id' => 10],
            ['ville' => 'Marrakech', 'region_id' => 7],
            ['ville' => 'Ait Daoud', 'region_id' => 7],
            ['ville' => 'Amizmiz', 'region_id' => 7],
            ['ville' => 'Assahrij', 'region_id' => 7],
            ['ville' => 'Aït Ourir', 'region_id' => 7],
            ['ville' => 'Ben Guerir', 'region_id' => 7],
            ['ville' => 'Chichaoua', 'region_id' => 7],
            ['ville' => 'El Hanchane', 'region_id' => 7],
            ['ville' => 'El Kelaâ des Sraghna', 'region_id' => 7],
            ['ville' => 'Essaouira', 'region_id' => 7],
            ['ville' => 'Fraïta', 'region_id' => 7],
            ['ville' => 'Ghmate', 'region_id' => 7],
            ['ville' => 'Ighounane', 'region_id' => 8],
            ['ville' => 'Imintanoute', 'region_id' => 7],
            ['ville' => 'Kattara', 'region_id' => 7],
            ['ville' => 'Lalla Takerkoust', 'region_id' => 7],
            ['ville' => 'Loudaya', 'region_id' => 7],
            ['ville' => 'Lâattaouia', 'region_id' => 7],
            ['ville' => 'Moulay Brahim', 'region_id' => 7],
            ['ville' => 'Mzouda', 'region_id' => 7],
            ['ville' => 'Ounagha', 'region_id' => 7],
            ['ville' => 'Sid L\'Mokhtar', 'region_id' => 7],
            ['ville' => 'Sid Zouin', 'region_id' => 7],
            ['ville' => 'Sidi Abdallah Ghiat', 'region_id' => 7],
            ['ville' => 'Sidi Bou Othmane', 'region_id' => 7],
            ['ville' => 'Sidi Rahhal', 'region_id' => 7],
            ['ville' => 'Skhour Rehamna', 'region_id' => 7],
            ['ville' => 'Smimou', 'region_id' => 7],
            ['ville' => 'Tafetachte', 'region_id' => 7],
            ['ville' => 'Tahannaout', 'region_id' => 7],
            ['ville' => 'Talmest', 'region_id' => 7],
            ['ville' => 'Tamallalt', 'region_id' => 7],
            ['ville' => 'Tamanar', 'region_id' => 7],
            ['ville' => 'Tamansourt', 'region_id' => 7],
            ['ville' => 'Tameslouht', 'region_id' => 7],
            ['ville' => 'Tanalt', 'region_id' => 9],
            ['ville' => 'Zeubelemok', 'region_id' => 7],
            ['ville' => 'Meknès‎', 'region_id' => 3],
            ['ville' => 'Khénifra', 'region_id' => 5],
            ['ville' => 'Agourai', 'region_id' => 3],
            ['ville' => 'Ain Taoujdate', 'region_id' => 3],
            ['ville' => 'MyAliCherif', 'region_id' => 8],
            ['ville' => 'Rissani', 'region_id' => 8],
            ['ville' => 'Amalou Ighriben', 'region_id' => 5],
            ['ville' => 'Aoufous', 'region_id' => 8],
            ['ville' => 'Arfoud', 'region_id' => 8],
            ['ville' => 'Azrou', 'region_id' => 3],
            ['ville' => 'Aïn Jemaa', 'region_id' => 3],
            ['ville' => 'Aïn Karma', 'region_id' => 3],
            ['ville' => 'Aïn Leuh', 'region_id' => 3],
            ['ville' => 'Aït Boubidmane', 'region_id' => 3],
            ['ville' => 'Aït Ishaq', 'region_id' => 5],
            ['ville' => 'Boudnib', 'region_id' => 8],
            ['ville' => 'Boufakrane', 'region_id' => 3],
            ['ville' => 'Boumia', 'region_id' => 8],
            ['ville' => 'El Hajeb', 'region_id' => 3],
            ['ville' => 'Elkbab', 'region_id' => 5],
            ['ville' => 'Er-Rich', 'region_id' => 5],
            ['ville' => 'Errachidia', 'region_id' => 8],
            ['ville' => 'Gardmit', 'region_id' => 8],
            ['ville' => 'Goulmima', 'region_id' => 8],
            ['ville' => 'Gourrama', 'region_id' => 8],
            ['ville' => 'Had Bouhssoussen', 'region_id' => 5],
            ['ville' => 'Haj Kaddour', 'region_id' => 3],
            ['ville' => 'Ifrane', 'region_id' => 3],
            ['ville' => 'Itzer', 'region_id' => 8],
            ['ville' => 'Jorf', 'region_id' => 8],
            ['ville' => 'Kehf Nsour', 'region_id' => 5],
            ['ville' => 'Kerrouchen', 'region_id' => 5],
            ['ville' => 'M\'haya', 'region_id' => 3],
            ['ville' => 'M\'rirt', 'region_id' => 5],
            ['ville' => 'Midelt', 'region_id' => 8],
            ['ville' => 'Moulay Ali Cherif', 'region_id' => 8],
            ['ville' => 'Moulay Bouazza', 'region_id' => 5],
            ['ville' => 'Moulay Idriss Zerhoun', 'region_id' => 3],
            ['ville' => 'Moussaoua', 'region_id' => 3],
            ['ville' => 'N\'Zalat Bni Amar', 'region_id' => 3],
            ['ville' => 'Ouaoumana', 'region_id' => 5],
            ['ville' => 'Oued Ifrane', 'region_id' => 3],
            ['ville' => 'Sabaa Aiyoun', 'region_id' => 3],
            ['ville' => 'Sebt Jahjouh', 'region_id' => 3],
            ['ville' => 'Sidi Addi', 'region_id' => 3],
            ['ville' => 'Tichoute', 'region_id' => 8],
            ['ville' => 'Tighassaline', 'region_id' => 5],
            ['ville' => 'Tighza', 'region_id' => 5],
            ['ville' => 'Timahdite', 'region_id' => 3],
            ['ville' => 'Tinejdad', 'region_id' => 8],
            ['ville' => 'Tizguite', 'region_id' => 3],
            ['ville' => 'Toulal', 'region_id' => 3],
            ['ville' => 'Tounfite', 'region_id' => 8],
            ['ville' => 'Zaouia d\'Ifrane', 'region_id' => 3],
            ['ville' => 'Zaïda', 'region_id' => 8],
            ['ville' => 'Ahfir', 'region_id' => 2],
            ['ville' => 'Aklim', 'region_id' => 2],
            ['ville' => 'Al Aroui', 'region_id' => 2],
            ['ville' => 'Aïn Bni Mathar', 'region_id' => 2],
            ['ville' => 'Aïn Erreggada', 'region_id' => 2],
            ['ville' => 'Ben Taïeb', 'region_id' => 2],
            ['ville' => 'Berkane', 'region_id' => 2],
            ['ville' => 'Bni Ansar', 'region_id' => 2],
            ['ville' => 'Bni Chiker', 'region_id' => 2],
            ['ville' => 'Bni Drar', 'region_id' => 2],
            ['ville' => 'Bni Tadjite', 'region_id' => 2],
            ['ville' => 'Bouanane', 'region_id' => 2],
            ['ville' => 'Bouarfa', 'region_id' => 2],
            ['ville' => 'Bouhdila', 'region_id' => 2],
            ['ville' => 'Dar El Kebdani', 'region_id' => 2],
            ['ville' => 'Debdou', 'region_id' => 2],
            ['ville' => 'Douar Kannine', 'region_id' => 2],
            ['ville' => 'Driouch', 'region_id' => 2],
            ['ville' => 'El Aïoun Sidi Mellouk', 'region_id' => 2],
            ['ville' => 'Farkhana', 'region_id' => 2],
            ['ville' => 'Figuig', 'region_id' => 2],
            ['ville' => 'Ihddaden', 'region_id' => 2],
            ['ville' => 'Jaâdar', 'region_id' => 2],
            ['ville' => 'Jerada', 'region_id' => 2],
            ['ville' => 'Kariat Arekmane', 'region_id' => 2],
            ['ville' => 'Kassita', 'region_id' => 2],
            ['ville' => 'Kerouna', 'region_id' => 2],
            ['ville' => 'Laâtamna', 'region_id' => 2],
            ['ville' => 'Madagh', 'region_id' => 2],
            ['ville' => 'Midar', 'region_id' => 2],
            ['ville' => 'Nador', 'region_id' => 2],
            ['ville' => 'Naima', 'region_id' => 2],
            ['ville' => 'Oued Heimer', 'region_id' => 2],
            ['ville' => 'Oujda', 'region_id' => 2],
            ['ville' => 'Ras El Ma', 'region_id' => 2],
            ['ville' => 'Saïdia', 'region_id' => 2],
            ['ville' => 'Selouane', 'region_id' => 2],
            ['ville' => 'Sidi Boubker', 'region_id' => 2],
            ['ville' => 'Sidi Slimane Echcharaa', 'region_id' => 2],
            ['ville' => 'Talsint', 'region_id' => 2],
            ['ville' => 'Taourirt', 'region_id' => 2],
            ['ville' => 'Tendrara', 'region_id' => 2],
            ['ville' => 'Tiztoutine', 'region_id' => 2],
            ['ville' => 'Touima', 'region_id' => 2],
            ['ville' => 'Touissit', 'region_id' => 2],
            ['ville' => 'Zaïo', 'region_id' => 2],
            ['ville' => 'Zeghanghane', 'region_id' => 2],
            ['ville' => 'Rabat', 'region_id' => 4],
            ['ville' => 'Salé', 'region_id' => 4],
            ['ville' => 'Ain El Aouda', 'region_id' => 4],
            ['ville' => 'Harhoura', 'region_id' => 4],
            ['ville' => 'Khémisset', 'region_id' => 4],
            ['ville' => 'Oulmès', 'region_id' => 4],
            ['ville' => 'Rommani', 'region_id' => 4],
            ['ville' => 'Sidi Allal El Bahraoui', 'region_id' => 4],
            ['ville' => 'Sidi Bouknadel', 'region_id' => 4],
            ['ville' => 'Skhirate', 'region_id' => 4],
            ['ville' => 'Tamesna', 'region_id' => 4],
            ['ville' => 'Témara', 'region_id' => 4],
            ['ville' => 'Tiddas', 'region_id' => 4],
            ['ville' => 'Tiflet', 'region_id' => 4],
            ['ville' => 'Touarga', 'region_id' => 4],
            ['ville' => 'Agadir', 'region_id' => 9],
            ['ville' => 'Agdz', 'region_id' => 8],
            ['ville' => 'Agni Izimmer', 'region_id' => 9],
            ['ville' => 'Aït Melloul', 'region_id' => 9],
            ['ville' => 'Alnif', 'region_id' => 8],
            ['ville' => 'Anzi', 'region_id' => 9],
            ['ville' => 'Aoulouz', 'region_id' => 9],
            ['ville' => 'Aourir', 'region_id' => 9],
            ['ville' => 'Arazane', 'region_id' => 9],
            ['ville' => 'Aït Baha', 'region_id' => 9],
            ['ville' => 'Aït Iaâza', 'region_id' => 9],
            ['ville' => 'Aït Yalla', 'region_id' => 8],
            ['ville' => 'Ben Sergao', 'region_id' => 9],
            ['ville' => 'Biougra', 'region_id' => 9],
            ['ville' => 'Boumalne-Dadès', 'region_id' => 8],
            ['ville' => 'Dcheira El Jihadia', 'region_id' => 9],
            ['ville' => 'Drargua', 'region_id' => 9],
            ['ville' => 'El Guerdane', 'region_id' => 9],
            ['ville' => 'Harte Lyamine', 'region_id' => 8],
            ['ville' => 'Ida Ougnidif', 'region_id' => 9],
            ['ville' => 'Ifri', 'region_id' => 8],
            ['ville' => 'Igdamen', 'region_id' => 9],
            ['ville' => 'Ighil n\'Oumgoun', 'region_id' => 8],
            ['ville' => 'Imassine', 'region_id' => 8],
            ['ville' => 'Inezgane', 'region_id' => 9],
            ['ville' => 'Irherm', 'region_id' => 9],
            ['ville' => 'Kelaat-M\'Gouna', 'region_id' => 8],
            ['ville' => 'Lakhsas', 'region_id' => 9],
            ['ville' => 'Lakhsass', 'region_id' => 9],
            ['ville' => 'Lqliâa', 'region_id' => 9],
            ['ville' => 'M\'semrir', 'region_id' => 8],
            ['ville' => 'Massa (Maroc)', 'region_id' => 9],
            ['ville' => 'Megousse', 'region_id' => 9],
            ['ville' => 'Ouarzazate', 'region_id' => 8],
            ['ville' => 'Oulad Berhil', 'region_id' => 9],
            ['ville' => 'Oulad Teïma', 'region_id' => 9],
            ['ville' => 'Sarghine', 'region_id' => 8],
            ['ville' => 'Sidi Ifni', 'region_id' => 10],
            ['ville' => 'Skoura', 'region_id' => 8],
            ['ville' => 'Tabounte', 'region_id' => 8],
            ['ville' => 'Tafraout', 'region_id' => 9],
            ['ville' => 'Taghzout', 'region_id' => 1],
            ['ville' => 'Tagzen', 'region_id' => 9],
            ['ville' => 'Taliouine', 'region_id' => 9],
            ['ville' => 'Tamegroute', 'region_id' => 8],
            ['ville' => 'Tamraght', 'region_id' => 9],
            ['ville' => 'Tanoumrite Nkob Zagora', 'region_id' => 8],
            ['ville' => 'Taourirt ait zaghar', 'region_id' => 8],
            ['ville' => 'Taroudannt', 'region_id' => 9],
            ['ville' => 'Temsia', 'region_id' => 9],
            ['ville' => 'Tifnit', 'region_id' => 9],
            ['ville' => 'Tisgdal', 'region_id' => 9],
            ['ville' => 'Tiznit', 'region_id' => 9],
            ['ville' => 'Toundoute', 'region_id' => 8],
            ['ville' => 'Zagora', 'region_id' => 8],
            ['ville' => 'Afourar', 'region_id' => 5],
            ['ville' => 'Aghbala', 'region_id' => 5],
            ['ville' => 'Azilal', 'region_id' => 5],
            ['ville' => 'Aït Majden', 'region_id' => 5],
            ['ville' => 'Beni Ayat', 'region_id' => 5],
            ['ville' => 'Béni Mellal', 'region_id' => 5],
            ['ville' => 'Bin elouidane', 'region_id' => 5],
            ['ville' => 'Bradia', 'region_id' => 5],
            ['ville' => 'Bzou', 'region_id' => 5],
            ['ville' => 'Dar Oulad Zidouh', 'region_id' => 5],
            ['ville' => 'Demnate', 'region_id' => 5],
            ['ville' => 'Dra\'a', 'region_id' => 8],
            ['ville' => 'El Ksiba', 'region_id' => 5],
            ['ville' => 'Foum Jamaa', 'region_id' => 5],
            ['ville' => 'Fquih Ben Salah', 'region_id' => 5],
            ['ville' => 'Kasba Tadla', 'region_id' => 5],
            ['ville' => 'Ouaouizeght', 'region_id' => 5],
            ['ville' => 'Oulad Ayad', 'region_id' => 5],
            ['ville' => 'Oulad M\'Barek', 'region_id' => 5],
            ['ville' => 'Oulad Yaich', 'region_id' => 5],
            ['ville' => 'Sidi Jaber', 'region_id' => 5],
            ['ville' => 'Souk Sebt Oulad Nemma', 'region_id' => 5],
            ['ville' => 'Zaouïat Cheikh', 'region_id' => 5],
            ['ville' => 'Tanger‎', 'region_id' => 1],
            ['ville' => 'Tétouan‎', 'region_id' => 1],
            ['ville' => 'Akchour', 'region_id' => 1],
            ['ville' => 'Assilah', 'region_id' => 1],
            ['ville' => 'Bab Berred', 'region_id' => 1],
            ['ville' => 'Bab Taza', 'region_id' => 1],
            ['ville' => 'Brikcha', 'region_id' => 1],
            ['ville' => 'Chefchaouen', 'region_id' => 1],
            ['ville' => 'Dar Bni Karrich', 'region_id' => 1],
            ['ville' => 'Dar Chaoui', 'region_id' => 1],
            ['ville' => 'Fnideq', 'region_id' => 1],
            ['ville' => 'Gueznaia', 'region_id' => 1],
            ['ville' => 'Jebha', 'region_id' => 1],
            ['ville' => 'Karia', 'region_id' => 3],
            ['ville' => 'Khémis Sahel', 'region_id' => 1],
            ['ville' => 'Ksar El Kébir', 'region_id' => 1],
            ['ville' => 'Larache', 'region_id' => 1],
            ['ville' => 'M\'diq', 'region_id' => 1],
            ['ville' => 'Martil', 'region_id' => 1],
            ['ville' => 'Moqrisset', 'region_id' => 1],
            ['ville' => 'Oued Laou', 'region_id' => 1],
            ['ville' => 'Oued Rmel', 'region_id' => 1],
            ['ville' => 'Ouazzane', 'region_id' => 1],
            ['ville' => 'Point Cires', 'region_id' => 1],
            ['ville' => 'Sidi Lyamani', 'region_id' => 1],
            ['ville' => 'Sidi Mohamed ben Abdallah el-Raisuni', 'region_id' => 1],
            ['ville' => 'Zinat', 'region_id' => 1],
            ['ville' => 'Ajdir‎', 'region_id' => 1],
            ['ville' => 'Aknoul‎', 'region_id' => 3],
            ['ville' => 'Al Hoceïma‎', 'region_id' => 1],
            ['ville' => 'Aït Hichem‎', 'region_id' => 1],
            ['ville' => 'Bni Bouayach‎', 'region_id' => 1],
            ['ville' => 'Bni Hadifa‎', 'region_id' => 1],
            ['ville' => 'Ghafsai‎', 'region_id' => 3],
            ['ville' => 'Guercif‎', 'region_id' => 2],
            ['ville' => 'Imzouren‎', 'region_id' => 1],
            ['ville' => 'Inahnahen‎', 'region_id' => 1],
            ['ville' => 'Issaguen (Ketama)‎', 'region_id' => 1],
            ['ville' => 'Karia (El Jadida)‎', 'region_id' => 6],
            ['ville' => 'Karia Ba Mohamed‎', 'region_id' => 3],
            ['ville' => 'Oued Amlil‎', 'region_id' => 3],
            ['ville' => 'Oulad Zbair‎', 'region_id' => 3],
            ['ville' => 'Tahla‎', 'region_id' => 3],
            ['ville' => 'Tala Tazegwaght‎', 'region_id' => 1],
            ['ville' => 'Tamassint‎', 'region_id' => 1],
            ['ville' => 'Taounate‎', 'region_id' => 3],
            ['ville' => 'Targuist‎', 'region_id' => 1],
            ['ville' => 'Taza‎', 'region_id' => 3],
            ['ville' => 'Taïnaste‎', 'region_id' => 3],
            ['ville' => 'Thar Es-Souk‎', 'region_id' => 3],
            ['ville' => 'Tissa‎', 'region_id' => 3],
            ['ville' => 'Tizi Ouasli‎', 'region_id' => 3],
            ['ville' => 'Laayoune‎', 'region_id' => 11],
            ['ville' => 'El Marsa‎', 'region_id' => 11],
            ['ville' => 'Tarfaya‎', 'region_id' => 11],
            ['ville' => 'Boujdour‎', 'region_id' => 11],
            ['ville' => 'Awsard', 'region_id' => 12],
            ['ville' => 'Oued-Eddahab', 'region_id' => 12],
            ['ville' => 'Stehat', 'region_id' => 1],
            ['ville' => 'Aït Attab', 'region_id' => 5],
        ];

        DB::table('villes')->insert($villes);
    }
}
